package io.github.johnjcool.keycloak.broker.cas.model;

public enum Code {
	INVALID_REQUEST,
	INVALID_TICKET_SPEC,
	UNAUTHORIZED_SERVICE_PROXY,
	INVALID_PROXY_CALLBACK,
	INVALID_TICKET,
	INVALID_SERVICE,
	INTERNAL_ERROR;
}