FROM jboss/keycloak:4.1.0.Final
MAINTAINER John J Cool <john.j.cool@gmail.com>

ADD keycloak-cas-services-$project_version.jar /opt/jboss/keycloak/standalone/deployments/keycloak-cas-services-$project_version.jar