FROM jboss/keycloak:4.8.3.Final
MAINTAINER John J Cool <john.j.cool@gmail.com>

ARG project_version=1.0.0

ADD keycloak-cas-services-$project_version.jar /opt/jboss/keycloak/standalone/deployments/keycloak-cas-services-$project_version.jar
